Deinit
readdle/system7 pull request #47
Opened 2021-01-24 19:17 UTC by pastey

Сварганил deinit. Предпоследний шаг на пути к IPO. Писал вечерами по две капли. Интересно что вы скажете

2021-02-01 08:33 UTC, salpieiev commented on system7/Commands/S7DeinitCommand.m
> +    help_puts("    Deletes all .s7*-files.");
Дефис точно нужен?)

2021-02-02 18:58 UTC, pastey commented on system7/Commands/S7DeinitCommand.m
> +    help_puts("    Deletes all .s7*-files.");
Убрал.

2021-02-02 21:18 UTC, pastey commented on system7/Utils/Utils.m
> +                                                               error:nil];
done

2021-02-02 21:18 UTC, pastey commented on system7/Utils/Utils.m
> +                                                              error:nil];
добавил

2021-02-02 21:19 UTC, pastey commented on system7-tests/deinitTests.m
> +while(0);
это вечная дилемма. Функция потом через сраку показывает ошибки, но дебажить удобней. Я пока выбираю макрос, если ты не против

2021-02-02 21:52 UTC, nikinapi requested changes
в общем - чётенько, чисто на поговорить вопросы

2021-02-02 21:52 UTC, nikinapi commented on system7/Commands/S7DeinitCommand.m
> +
может удалить из .gitignore все зависимости?
плюсы: юзер охуеет от происходящего и точно что-то сделает с этими папками
минусы: юзер охуеет

2021-02-02 21:52 UTC, nikinapi commented on system7-tests/deinitTests.m
> +while(0);
какой охуенный макрос! здоровенный сука!
https://cs.pikabu.ru/post_img/2013/10/25/9/1382712527_1028141722.jpg

ну вообще соглашусь, с функциёвиной не так удобно выгребать, где отвалилось. 
но что если использовать обычные ассерты, а на вызов этой функции поставить `XCTAssertNoThrow`?

2021-02-03 07:34 UTC, salpieiev submitted a review, later dismissed

2021-02-04 08:24 UTC, pastey commented on system7/Commands/S7DeinitCommand.m
> +
а вот это ты прям четко подметил. Это, я бы сказал, проебация с моей стороны. Сделаю

2021-02-04 08:28 UTC, pastey commented on system7-tests/deinitTests.m
> +while(0);
Короче, раз это место вызывает столько вопросов – переделаю на функцию

2021-02-04 09:58 UTC, nikinapi approved these changes

2021-02-04 12:22 UTC, salpieiev approved these changes

2021-02-04 13:20 UTC, merged