Add global and system options support
readdle/system7 pull request #56
Opened 2021-11-26 14:51 UTC by apodrugin

Add ability to set global s7 options, i.e. save/load them to/from **~/.s7options** file. Also now it is possible to set system wide options in **/etc/s7options** file.

2021-11-26 14:54 UTC, apodrugin commented on system7-tests/integration/case28-addDoesntAllowToAddSubrepoWithForbiddenTransportProtocolInSystemOptions.sh
> +S7_SYSTEM_OPTIONS_PATH="/etc/s7options"
This test requires 'root' privileges to be run, because we access /etc directory. Thus now test.sh should be run using sudo.

2021-11-26 14:54 UTC, apodrugin commented on system7-tests/integration/case30-addRepoOptionsOverwriteSystemOptions.sh
> +S7_OPTIONS_PATH=".s7options"
Same sudo requirement...

2021-11-26 14:54 UTC, apodrugin commented on system7-tests/integration/case31-addGlobalOptionsOverwriteSystemOptions.sh
> +S7_SYSTEM_OPTIONS_PATH="/etc/s7options"
Same sudo requirement...

2021-11-26 15:05 UTC, pastey commented on system7-tests/integration/case31-addGlobalOptionsOverwriteSystemOptions.sh
> +S7_SYSTEM_OPTIONS_PATH="/etc/s7options"
напрашивается простое предложение... убить возможность сунуть s7options в /etc
я не знаю людей в здравом уме, которые у нас будут таким заниматься

2021-11-26 15:12 UTC, apodrugin commented on system7-tests/integration/case31-addGlobalOptionsOverwriteSystemOptions.sh
> +S7_SYSTEM_OPTIONS_PATH="/etc/s7options"
Воспроизводил возможности git. Могу убрать, если это не нужно нам.

2021-11-26 16:05 UTC, pastey requested changes
Андрюха, спасибо большое! Это очень круто!

Есть пару предложенией.

2021-11-26 16:05 UTC, pastey commented on system7-tests/integration/case29-addRepoOptionsOverwriteGlobalOptions.sh
> +setTestOptionsFileContent "$S7_GLOBAL_OPTIONS_PATH" "[add]\ntransport-protocols = https, http"
Есть два предложения как это дело организовать.

1. как минимум заюзать trap. Тогда если тест завалится, не придется руками чинить у себя на машине . s7options

```
function cleanup {
   restoreOriginalOptionsFileContent "$S7_GLOBAL_OPTIONS_PATH"
}

trap cleanup EXIT
```

2. в идеале хочется, чтобы во время выполнения тестов можно было продолжать пользоваться своей машиной. Я думал, что можно завести в коде маленький backdoor – переменную окружения а-ля S7_USER_OPTIONS_PATH. Если она есть, то читаем опции не из ~/.s7options, а из пути, который сидит в переменной. В тестах ставим эту переменную (и можем и не сбрасывать, т.к. на родительский скрипт/шелл она никак не повлияет.

2021-11-26 16:17 UTC, apodrugin commented on system7-tests/integration/case29-addRepoOptionsOverwriteGlobalOptions.sh
> +setTestOptionsFileContent "$S7_GLOBAL_OPTIONS_PATH" "[add]\ntransport-protocols = https, http"
попробую второй вариант.

2021-11-26 16:19 UTC, apodrugin commented on system7/Types/Options/S7IniConfigOptions.m
> +    NSString *allowedProtocolsString = iniDict[S7IniConfigOptionsAddCommandSectionName][S7IniConfigOptionsAddCommandAllowedTransportProtocols].lowercaseString;
ок. буду выводить ошибку в этом случае в stderr

2021-11-26 16:22 UTC, apodrugin commented on system7/Types/Options/S7Options.m
> +    addIniConfigOptionsIfPossible(S7GlobalOptionsFilePath);
переименую

2021-11-26 16:27 UTC, apodrugin commented on system7/Types/Options/S7Options.m
> +#define S7GlobalOptionsFilePath [[NSString stringWithUTF8String:getenv("HOME")] stringByAppendingPathComponent:S7OptionsFileName]
Тогда поддержку настроек в /etc удаляю. На sudo забиваю. Хотя, конечно, интересно себя вдет sudo: ты вроде бы как выполняешь скрипт под видом другого пользователя, но переменные окружения у тебя от текущего пользователя остаются.

2021-11-26 16:51 UTC, apodrugin commented on system7/Types/Options/S7IniConfigOptions.m
> +    NSString *allowedProtocolsString = iniDict[S7IniConfigOptionsAddCommandSectionName][S7IniConfigOptionsAddCommandAllowedTransportProtocols].lowercaseString;
Сейчас ошибка уже выводится если не указать значение. При парсинге, если пользователь не проставил значение для ключа, то мы считаем что это бул и записываем значение "true" в словарь. В кодах такой коммент:
> from https://git-scm.com/docs/git-config
>"All the other lines (and the remainder of the line after the section header)
>are recognized as setting variables, in the form name = value
>(or just name, which is a short-hand to say that the variable is the boolean "true")"

При этом в stderr выведем сообщение:
error: unsupported transport protocol(s) detected during 'transport-protocols' option parsing: 'true'

Предлагаю так и оставить.

2021-11-26 19:54 UTC, pastey commented on system7/Types/Options/S7IniConfigOptions.m
> +    NSString *allowedProtocolsString = iniDict[S7IniConfigOptionsAddCommandSectionName][S7IniConfigOptionsAddCommandAllowedTransportProtocols].lowercaseString;
Поддерживаю 😂
Можно сказать, что я перестарался, когда писал парсер, но уже и бог с ним

2021-11-26 19:58 UTC, pastey commented on system7/Types/Options/S7Options.m
> +#define S7GlobalOptionsFilePath [[NSString stringWithUTF8String:getenv("HOME")] stringByAppendingPathComponent:S7OptionsFileName]
Я как-то об этом иногда е задумывался. Если подумать, то я понимаю это так -- переменные окружения принадлежат процессу, и sudo отнаследовал их от шелла. Видимо часть переменных он подкручивает (типа HOME), а за остальное не парится

2021-11-29 08:50 UTC, apodrugin commented
Внес правки. Прошу прожать

2021-11-30 09:56 UTC, pastey approved these changes
Круто! Спасибо большое, Адрюха!

Я чуть удивлен, что тильда работает, но раз работает, то и бог с ней. Если найдем прецеденты багов, тогда можно будет усложнить.

2021-11-30 10:02 UTC, merged