Create tests.yml
readdle/system7 pull request #61
Opened 2022-05-06 14:26 UTC by nikinapi

2022-05-06 14:32 UTC, pastey approved these changes
Not bad!

2022-05-06 15:08 UTC, pastey commented
Пушка-рокета! Если там еще и shell-тесты запустить – вообще будет огинь!

2022-05-06 15:10 UTC, nikinapi commented
подожди радоваться, я ещё не закончил эту шляпу пинать)

2022-05-09 07:37 UTC, pastey requested changes
Шик! Пара вопросов

2022-05-09 07:37 UTC, pastey commented on system7/Merge Driver/S7ConfigMergeDriver.m
> +                        break;
Предлагаю тут поставить exit с ошибкой. Иначе мы тихонечко будем делать... что-то

2022-05-09 07:37 UTC, pastey commented on .github/workflows/tests.yml
> +          git config --global pull.rebase false
а зачем это нужно?

2022-05-09 09:51 UTC, nikinapi commented on system7/Merge Driver/S7ConfigMergeDriver.m
> +                        break;
мы тут тихонечко провалимся в ожидание юзерского инпута

2022-05-09 09:52 UTC, nikinapi commented on .github/workflows/tests.yml
> +          git config --global pull.rebase false
на гитхабовских машинах тот же ворнинг насчёт стратегии пула, но он приводит к падению скрипта

2022-05-09 10:59 UTC, pastey approved these changes

2022-05-09 10:59 UTC, pastey commented on .github/workflows/tests.yml
> +          git config --global pull.rebase false
понял

2022-05-09 10:59 UTC, pastey commented on system7/Merge Driver/S7ConfigMergeDriver.m
> +                        break;
еба-боба. Не постиг глубин!
nit: можно писать ворнинг. Если кто-то забыл что поставил у себя такую переменную окружения.

2022-05-10 07:45 UTC, aishchenko-readdle requested changes
LGTM, but have one suggestion.

2022-05-10 07:45 UTC, aishchenko-readdle commented on system7/Merge Driver/S7ConfigMergeDriver.m
> +                        break;
nit: выглядит замысловато с 
```
do {
}
while(0);
```
и 
`break;`.

Я думаю что часть кодов можно вынести в отдельную функцию и там написать return(вместо `break;`).
Будет понятно как это все работает.
Сейчас это не очевидно и логика сохранится до первого рефакторинга, где человек не поймет как это все работает и поломает.

Например функция:
`- (BOOL)getEnvironmentResolutionResult:(S7ConflictResolutionOption *)resolutionResult`.
Если она вернула NO. То не делаем `return resolution;` внутри этой функции и проваливаемся на ввод.

2022-05-10 09:37 UTC, aishchenko-readdle approved these changes
Выглядит ок. 👍

2022-05-10 09:38 UTC, pastey approved these changes

2022-05-10 09:46 UTC, merged