Add filter support
readdle/system7 pull request #64
Opened 2022-11-03 09:07 UTC by dsafronov01

2022-11-04 13:21 UTC, pastey requested changes
По сути вопросов нет. Все классно, все будет работать 👍 

Мне не заходит ООП с S7FilterProtocol.

Предлагаю завести enum GitFilter { S7GitFilterNoFilter, S7GitFilterBlobNone }. Может   GitExchangeFilter – хорошее название не приходит в голову, так что если что и GitFilter сойдет. Без префикса S7. По моей задумке Git.h/m немного в стороне, и не завязаны на S7. Передавать в clone/fetch S7GitFilter вместо бульки.

В S7IniConfigOptions id<S7FilterProtocol> заменить на NSNumber * filter, который под капотом будет содержать GitFilter. В S7DefaultOptions filter -> @(S7GitFilterBlobNone);

Суть останется та же, но я буду спокойнее.

2022-11-04 13:21 UTC, pastey commented on system7/Types/Options/S7IniConfigOptions.m
> +            NSMutableString *errorMessage =
там где ты вдохновлялся была необходимость в Mutable строке, т.к. там дописываю в строку перечень опций. Тебе эта строка в целом не сильно нужна – fprintf тоже принимает формат, и ты все это можешь сразу сделать там

2022-11-04 13:21 UTC, pastey commented on system7-tests/iniConfigOptionsParsingTests.m
> +- (void)testCorrectFilterBlobNoneParsing {
Предлагаю еще добавить тест на случай
```
[git]
filter =
```
см. `testEmptyValueIsTreatedAsTrue`. Хочется быть увереным, что это в этом случае тоже будет `XCTAssertNil(options.filter);`

2022-11-07 08:51 UTC, pastey requested changes

2022-11-07 08:51 UTC, pastey commented on system7-tests/iniConfigOptionsParsingTests.m
> +    XCTAssertEqual(options.filter, GitFilterNone);
тут None, а 👇  Unspecified. Мне кажется должно быть что-то одно

2022-11-07 08:51 UTC, pastey commented on system7/Types/Options/S7DefaultOptions.m
> +    return GitFilterUnspecified;
тут должен быть None по-дефолту

2022-11-07 08:51 UTC, pastey commented on system7/Types/Options/S7IniConfigOptions.m
> +            _filter = GitFilterNone;
тут должен быть Unspecified в таком случае. Этот уровень обосрался – даем возможность отработать следующему уровню

2022-11-07 08:51 UTC, pastey commented on system7/git/Git.m
> +    NSString *filterBlobNoneOption = @"";
```suggestion
    NSString *filterOption = @"";
```

2022-11-07 08:51 UTC, pastey commented on system7/git/Git.m
> +    NSString *filterBlobNoneOption = @"";
```suggestion
    NSString *filterOption = @"";
```

2022-11-07 09:43 UTC, pastey approved these changes
Супер! 👍 
Ща натыкаю на Jenkins-ах конфиг, и маякну тебе, когда можно будет мержить

2022-11-10 11:42 UTC, nikinapi requested changes

2022-11-10 11:42 UTC, nikinapi commented on system7/git/GitFilter.h
> +    GitFilterNone,
звучит как одно и то же. может удалить none?

2022-11-10 11:42 UTC, nikinapi commented on system7/git/GitFilter.m
> +NSString * const kGitFilterBlobNone = @"blob:none";
эта константа почему-то используется только при парсинге конфига, дальше везде захардкожено

2022-11-10 11:42 UTC, nikinapi commented on system7/Types/Options/S7IniConfigOptions.m
> +@property (nonatomic, assign) BOOL areFilterParsed;
nit: isFilterParsed

2022-11-10 11:42 UTC, nikinapi commented on system7/Types/Options/S7DefaultOptions.m
> +    return GitFilterNone;
я бы предложил перейти от енама к строчным константам, потому что это неполноценное решение, которое поддерживает исключительно один фильтр

2022-11-10 13:08 UTC, dsafronov01 commented on system7/git/GitFilter.h
> +    GitFilterNone,
Это немного разные сущности.
`GitFilterUnspecified` - дает нам понимание того, что значения действительно нет в конфиге, а не как дефолтное состояние, которым является `GitFilterNone`.

2022-11-10 13:10 UTC, dsafronov01 commented on system7/git/GitFilter.m
> +NSString * const kGitFilterBlobNone = @"blob:none";
Я правильно понимаю, что ты предлагаешь добавить ее использование [тут](https://github.com/readdle/system7/pull/64/files#diff-564de27e0386750af84adcc3ca0f14958a3f180f3e165f43a13027f9a870abfcR149) и [тут](https://github.com/readdle/system7/pull/64/files#diff-564de27e0386750af84adcc3ca0f14958a3f180f3e165f43a13027f9a870abfcR988)?

2022-11-10 13:29 UTC, nikinapi commented on system7/git/GitFilter.m
> +NSString * const kGitFilterBlobNone = @"blob:none";
да

2022-11-10 14:56 UTC, dsafronov01 commented on system7/git/GitFilter.h
> +    GitFilterNone,
Если я тебя правильно понимаю, то таким образом появится зависимость на последовательности массива `optionsChain`, что, на мой взгляд, нехорошо.

2022-11-10 15:07 UTC, dsafronov01 commented on system7/Types/Options/S7IniConfigOptions.m
> +@property (nonatomic, assign) BOOL areFilterParsed;
Спасибо, поправил.

2022-11-10 15:07 UTC, nikinapi commented on system7/git/GitFilter.h
> +    GitFilterNone,
так в этом и суть optionsChain - вернуть первое подходящее значение, либо значение по умолчанию

2022-11-10 15:07 UTC, dsafronov01 commented on system7/git/GitFilter.m
> +NSString * const kGitFilterBlobNone = @"blob:none";
Спасибо, поправил.

2022-11-11 08:07 UTC, pastey commented on system7/git/GitFilter.h
> +    GitFilterNone,
Я бы оставлял все как есть:
- Unspecified – ничего не указано. Делайте что хотите – пользователю насрать
- None – четко сказано – "не используйте фильтры". Default у нас возвращает его
- BlobNone – понятно

2022-11-11 10:57 UTC, pastey approved these changes

2022-11-11 11:14 UTC, pastey commented on system7/Types/Options/S7DefaultOptions.m
> +    return GitFilterNone;
сознательно так просил Данила сделать. Я думаю, что мы никогда не добавим другие фильтры

2022-11-11 11:17 UTC, nikinapi approved these changes

2022-11-11 11:17 UTC, nikinapi commented on system7/git/GitFilter.h
> +    GitFilterNone,
ок

2022-11-11 11:17 UTC, nikinapi commented on system7/Types/Options/S7DefaultOptions.m
> +    return GitFilterNone;
штош...

2022-11-11 15:11 UTC, merged