Sped up post-checkout hook in case subrepo path was changed while origin remained the same by moving it instead of re-cloning
readdle/system7 pull request #65
Opened 2023-04-13 14:56 UTC by nikinapi

2023-04-13 20:05 UTC, pastey requested changes
Идею горячо поддреживаю!

Вижу пару проблем.

И самое главное – прошу написать тесты. Вся s7 покрыта тестами, и в этом ее сила. Иначе потом вносить новые правки будем со скрещенными пальцами. Понимаю, что писать их лень, но я сам не пычкаю пару изм-й уже несколько месяцев потому что нужно написать тесты, и без тестов я их сам себе не пропущу.

2023-04-13 20:05 UTC, pastey commented on system7/Hooks/S7PostCheckoutHook.m
> +                                                 error:nil];
Проверка ошибок... не очень ))))

```suggestion
                                                 error:&error];
```

2023-04-13 20:05 UTC, pastey commented on system7/Hooks/S7PostCheckoutHook.m
>      const int deleteExitCode = [self deleteSubrepos:subreposToDelete.allValues];
Есть ощущение, что в этом случае  deleteSubrepos выйдет с ошибкой, и весь post-checkout будет считаться зафейленым. На локальной машине может на это насрать, а где-то на Jenkins-е это может привести к спонтанному зафейленному билду.

2023-04-14 06:57 UTC, salpieiev reviewed
Паша уже все откомментировал :)

2023-04-14 15:35 UTC, nikinapi commented on system7/Hooks/S7PostCheckoutHook.m
>      const int deleteExitCode = [self deleteSubrepos:subreposToDelete.allValues];
delete тоже фейлится только в случае неудачного вызова `NSFileManager`. улучшил обработку ошибок (т.е. добавил её)

2023-04-14 15:36 UTC, nikinapi commented
тесты, само собой, будут. one step at a time, у меня локально они почему-то фейлятся и тут тоже не всё проходит, сначала их починю

2023-04-18 11:07 UTC, nikinapi commented on system7/Hooks/S7PostCommitHook.m
> +    if (NO == [repo shouldExecutePostCommitHook]) {
не знаю, как раньше работали тесты, потому что они все рассчитывали, что сабрепы зачекаутят, но пост-коммит должен был тут выходить, что он и начал делать при прогонке тестов в этом ПР.
```
case-cherryPickMultipleCommitsNoMerge.sh
case-cherryPickSingleCommitNoMerge.sh
case-revertSubrepoAddCommit.sh
case-revertSubrepoUpdateCommit.sh
```

2023-04-18 11:36 UTC, pastey requested changes
Спасибо большое!
Не смог все-таки не запросить еще одну правочку 🙏

2023-04-18 11:36 UTC, pastey commented on system7/Hooks/S7PostCommitHook.m
> +    if (NO == [repo shouldExecutePostCommitHook]) {
Удивительный факт

2023-04-18 11:36 UTC, pastey commented on system7/Hooks/S7PostCommitHook.m
> +    if (NO == [repo shouldExecutePostCommitHook]) {
Спасибо за фикс.
Все-таки прошу немного переделать.
По моей (нигде не задокументированой) задумке, Git – это чисто обертка над... Git-ом. Проверка такая – ты можешь взять этот Git, и использовать его потом в другом проекте. Новый метод очень с натяжкой конечно проходит эту проверку – ты можешь взять этот класс, и не использовать метод `shouldExecutePostCommitHook` :)

Предлагаю:
- в этом классе добавить метод shouldExecutePostCommitHook
- в Git добавить два метода – isMergeRevision, и isCherryPickOrRevert, и использовать их для реализации shouldExecutePostCommitHook

2023-04-18 11:36 UTC, pastey commented on system7/Hooks/S7PostCheckoutHook.m
> +            fprintf(stderr,
Было бы круто, если тебе не сложно, сделать этот output красным 🙏

2023-04-18 11:36 UTC, pastey commented on system7-tests/checkoutTests.m
> +        NSDate *(^getCreationDate)(NSString *) = ^(NSString *path){
nit: есть риск, что все сработает очень быстро, и на самом деле эта дата будет одинаковой и в случае успеха, и в случае провала. Можно завязаться на inode (NSFileSystemFileNumber).

2023-04-19 08:50 UTC, nikinapi commented on system7/Hooks/S7PostCheckoutHook.m
> +            fprintf(stderr,
в другой раз

2023-04-19 09:22 UTC, pastey approved these changes
Идеально. Спасибо!
❤️

2023-04-19 11:13 UTC, salpieiev approved these changes
👍

2023-04-19 11:17 UTC, merged