fix concurrent use of cwd during checkout
readdle/system7 pull request #74
Opened 2024-01-29 21:17 UTC by pastey

При очередном мерже s7 упал на ассерте:
```
 NSAssert(NSThread.isMainThread,
             @"if someday this code gets parrallelized, we will have to remove `executeInDirectory` here."
              "Different threads will mess with it, resulting in undefined (read bad) checkout/init results.");
```

В процессе чекаута, если сабрепа сама является s7 репой, на ней делается дополнительный init. S7InitCommand был написан в те дивные времена, когда можно было взять текущую папку, и в ней работать со служебными файлами s7 и git-а. Когда я сделал checkout параллельным, я почему-то решил, что кейс с init-ом не может произойти параллельно, поэтому можно не трогать S7InitCommand, и не избавлять его от наивного использования CWD. Я оставлял этот ассерт чтобы если что отловить, если S7InitCommand таки юзается с разных потоков при параллельной работе чекаута. И вот оно меня нашло.

Самое интересное. На этот код есть тест, но в тесте ровно одна сабрепа с вложенной сабрепой. Как я сегодня узнал, `dispatch_apply` в случае одного элемента в массиве не порождает новых потоков, а просто выполняет одну итерацию прямо на вызвавшем потоке. Поэтому наш тест не тестировал реальной многопоточной работы checkout (на самом деле reset). Пропатчил тест, чтобы там было больше сабреп (целых две 😂 ).

Ну, а дальше собственно нужно было приучить S7InitCommand работать на абсолютных путях. Дописал соотв-й тест. Слегка усилил существующие проверки в тестах – не все куски кода оказались покрыты.

2024-01-29 21:20 UTC, pastey commented on system7-tests/initTests.m
> -        BOOL isDirectory = NO;
Этот шмат вынес в отдельный метод. В нем добавил еще пару проверок, которых не хватало.

2024-01-29 21:20 UTC, pastey commented on system7/Commands/S7InitCommand.m
> -int addLineToGitAttributes(NSString *lineToAppend) {
Унес в utils. И уже там добавил аргумент для работы на абсолютных путях

2024-01-30 12:32 UTC, nikinapi requested changes
yes but

2024-01-30 12:32 UTC, nikinapi commented on system7/Utils/Utils.h
>  int removeLinesFromGitIgnore(NSSet<NSString *> *linesToRemove);
остальные функции продолжают работать в current working directory

2024-01-30 12:32 UTC, nikinapi commented on system7/Utils/Utils.m
> +    }
предлагаю просто сабстринг поискать. так же возможны эдж кейсы, что lineToAdd будет c `\n`, а в `existingLines` его не будет (как и в `newContent` может не быть)

2024-01-30 12:32 UTC, nikinapi commented on system7/Commands/S7InitCommand.h
> +- (int)runWithArguments:(NSArray<NSString *> *)arguments inRepo:(GitRepository *)repo;
может сделать это дефолтным интерфейсом команды? всегда явно передавать репозиторий

2024-01-30 12:32 UTC, nikinapi commented on system7/Hooks/S7PostCheckoutHook.m
> -        executeInDirectory(subrepoGit.absolutePath, ^int{
предлагаю убрать вызовы этой функции из кодов s7, оставить только в тестах, где мы уверены в последовательности действий

2024-01-30 12:43 UTC, pastey commented
> yes but

Все что ты предлагаешь это хорошо и правильно. Только это все отдельные задачи, которые надо делать отдельно. В рамках этого ПР-а могу их лишь зафиксировать в бэклоге.

2024-01-30 12:43 UTC, pastey commented on system7/Utils/Utils.h
>  int removeLinesFromGitIgnore(NSSet<NSString *> *linesToRemove);
да. Задачи переписать весь проект передо мной не было.

2024-01-30 12:44 UTC, pastey commented on system7/Utils/Utils.m
> +    }
Функцию перенес без каких-либо изм-й в логике. Ее рефакторинг не входит в эту задачу

2024-01-30 12:45 UTC, pastey commented on system7/Commands/S7InitCommand.h
> +- (int)runWithArguments:(NSArray<NSString *> *)arguments inRepo:(GitRepository *)repo;
Good point. Но это надо взорвать все команды и все тесты

2024-01-30 12:45 UTC, pastey commented on system7/Hooks/S7PostCheckoutHook.m
> -        executeInDirectory(subrepoGit.absolutePath, ^int{
Такой вызов остался ровно один – в S7AddCommand. Там можно переписать, но предварительно надо дописать тестов. За пределами этого бага

2024-01-30 13:34 UTC, nikinapi approved these changes

2024-01-30 13:34 UTC, nikinapi commented
> могу их лишь зафиксировать в бэклоге

годится

2024-01-30 13:45 UTC, salpieiev approved these changes

2024-01-30 13:58 UTC, merged