Cleanup
readdle/system7 pull request #78
Opened 2024-02-16 22:21 UTC by pastey

2024-02-17 14:04 UTC, zrxq approved these changes

2024-02-21 15:48 UTC, apodrugin requested changes

2024-02-21 15:48 UTC, apodrugin commented on system7/Commands/S7InitCommand.m
> +        return S7ExitCodeGitOperationFailed;
А чего тут S7ExitCode**Git**OperationFailed, а не S7ExitCodeFileOperationFailed? Это же не Гит виноват, что там папка лежит... Ниже есть файлы с такой же логикой, в которых нужно поправить, если что.

2024-02-21 16:50 UTC, pastey commented on system7/Commands/S7InitCommand.m
> +        return S7ExitCodeGitOperationFailed;
Тут чисто философский вопрос. Я смотрю на эту функцию как на что-то типа `git config`, только сделанный нами на коленке (и в каличном месте, но это уже выходит за скоуп задачи этого ПР-а).
Поэтому я считаю, что тут Git ошибка семантически норм.
По большому счету – главное чтоб не Success 😂

2024-02-21 16:51 UTC, pastey commented on system7/Commands/S7InitCommand.m
> +        return S7ExitCodeGitOperationFailed;
Если будете сильно философствовать – поддамся уговорам и сделаю что хотите.

2024-02-22 09:43 UTC, apodrugin approved these changes
:soydet:

2024-02-22 09:43 UTC, merged