EXP-13070: Update s7 to checkout subrepos in case of merge conflicts
readdle/system7 pull request #85
Opened 2024-12-05 22:16 UTC by Piranja

https://readdle-j.atlassian.net/browse/EXP-13070

Тепер у випадку конфліктів у `.s7substate` робиться checkout тим сабрепам які змержились без конфлікту.
Додав uint & integration tests.

2024-12-05 22:19 UTC, Piranja commented on system7/Hooks/S7PostCheckoutHook.m
> +            fromConfig = [self makeConfigWithConfig:fromConfig removingSubrepoDescriptions:subrepoConflicts];
Трохи не люблю міняти значення для input variables, але з іншого боку не хочеться префікси додавати і писати щось таке: 
```
toConfig:(S7Config *)aToConfig
S7Config *toConfig = aToConfig
``` 

Подумав, що переприсвоїти буде меншим злом. Якщо що - відкритий до пропозицій

2024-12-05 22:24 UTC, Piranja commented on system7/Types/S7SubrepoDescription.h
> +@property (nonatomic, readonly) BOOL hasConflict;
Щоб не перевіряти на `isKindOfClass:[S7SubrepoDescriptionConflict class]` додав проперю

2024-12-06 11:49 UTC, pastey requested changes

2024-12-06 11:49 UTC, pastey commented on system7-tests/mergeDriverTests.m
> +        GitRepository *pdfkitSubrepoGit = [GitRepository repoAtPath:@"Dependencies/RDPDFKit"];
Please, check if the ReaddleLib is actually in the conflict state (maybe add a utility function to the `GitRepository` class)

2024-12-06 11:49 UTC, pastey commented on system7/Hooks/S7PostCheckoutHook.m
> +            fromConfig = [self makeConfigWithConfig:fromConfig removingSubrepoDescriptions:subrepoConflicts];
Пропоную замість цього, в місці 

```
    dispatch_apply(subreposToCheckout.count, DISPATCH_APPLY_AUTO, ^(size_t i) {
        S7SubrepoDescription *subrepoDesc = subreposToCheckout[i];
```

превірити S7SubrepoDescConflict + shouldSkipConflicts, і зробити або s7logWarn("skipping conflict") + return або, якщо NO == shouldSkipConflicts, тоді logError + `recordFailingExitCode`

2024-12-10 13:47 UTC, Piranja commented
Після сьогоднішнього обговорення і змін мені реалізація подобається більше

2024-12-11 08:57 UTC, pastey requested changes
Саша, дуже дякую!

Мене все ж муляє о той `hasConflict` у S7SubrepoDescription. Можна все ж попросити його прибрати, і фактично в одному місці написати isKindOfClass? Ти не проти?

2024-12-11 09:41 UTC, Piranja commented
> Саша, дуже дякую!
> 
> Мене все ж муляє о той `hasConflict` у S7SubrepoDescription. Можна все ж попросити його прибрати, і фактично в одному місці написати isKindOfClass? Ти не проти?

Так, звичайно. Зараз зроблю

2024-12-11 11:02 UTC, pastey commented on system7-tests/integration/case-mergeConflictInSubrepo-keepConflict.sh
> +assert test $(git -C Dependencies/RDGeometry rev-parse HEAD) == $RDGEOMETRY_REVISION
Забув про це написати. Мене дивує яким дивом воно працює. У `test` нема ==. Там є тільки =

```suggestion
assert test $(git -C Dependencies/RDGeometry rev-parse HEAD) = $RDGEOMETRY_REVISION
```

2024-12-11 11:02 UTC, pastey commented on system7-tests/integration/case-mergeConflictInSubrepo-keepConflict.sh
> +assert test $(git -C Dependencies/RDPDFKit rev-parse HEAD) == $RDPDFKIT_REVISION
```suggestion
assert test $(git -C Dependencies/RDPDFKit rev-parse HEAD) = $RDPDFKIT_REVISION
```

2024-12-11 11:03 UTC, pastey approved these changes

2024-12-11 11:03 UTC, merged